/// ═══════════════════════════════════════════════════════════════
/// AUTO-GENERATED by BotForge — DO NOT EDIT MANUALLY
/// Organisation: Acme Corporation (e16bf8b7-b281-49a7-b1fb-cfbac7fcf942)
/// Generated: 2026-04-27T20:52:56.572Z
/// Chatbot ID: 3b8deb5e-5a71-43ee-ba53-9d781ed54298
/// API Key: 
/// ═══════════════════════════════════════════════════════════════
library;

class AppConfig {
  AppConfig._();

  // ── Brand Identity ──────────────────────────────────────────────
  static const String businessName   = 'Acme Corporation';
  static const String tagline        = '';
  static const String botName        = 'Acme Assistant';
  static const String botRole        = 'Customer Experience Assistant';
  static const String welcomeMessage = 'Hey, welcome to auto stores';

  static const List<String> quickReplies = [
    '💰 Pricing & Plans',
    '🛠️ Our Services',
    '📞 Contact Support'
  ];

  // ── Visuals ──────────────────────────────────────────────────────
  static const String primaryColorHex = '#FF5733';
  static const String accentColorHex  = '#33FF57';
  static const String botAvatarAsset  = 'assets/images/bot_avatar.png';
  static const String logoAsset       = 'assets/images/logo.png';

  // ── Backend ──────────────────────────────────────────────────────
  static const String apiBaseUrl     = 'https://api.botforge.app';
  static const String chatEndpoint   = '/chatbots/mobile/:chatbotId';
  static const String organisationId = 'e16bf8b7-b281-49a7-b1fb-cfbac7fcf942';
  static const String chatbotId = '3b8deb5e-5a71-43ee-ba53-9d781ed54298';
  static const String apiKey = '';

  // ── Chat Session ────────────────────────────────────────────────
  static const String chatId = '';  // Generated on first chat

  // ── Business Hours ───────────────────────────────────────────────
  static const bool   showBusinessHours = false;
  static const String businessHours     = '';
  static const String offlineMessage    =
      'We are currently outside business hours. I will still do my best to help, '
      'but a human agent will follow up. 🌙';

  // ── Social / Contact ─────────────────────────────────────────────
  static const String whatsappNumber  = '';
  static const String telegramHandle  = '';
  static const String supportEmail    = '';
  static const String websiteUrl      = '';

  // ── Feature Flags ─────────────────────────────────────────────────
  static const bool enableFileAttachments = true;
  static const bool enableVoiceMessages   = false;
  static const bool enableRatings         = true;
  static const bool enableTypingIndicator = true;
  static const bool enableReadReceipts    = true;
}